version: '3.8'

services:
  api:
    container_name: linhadigitiavel2data-app
    build:
      context: .
      dockerfile: ./.Dockerfile
    environment:
      NODE_ENV: development
      NODE_PATH: .
      CONTEXT_PATH: /api/v1
      PORT: 3000

    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
